# ============================================================
# raster_to_mapbox_tileset_svy21.py
#
# Purpose:
#   1. Take an input GeoTIFF (e.g. comfort / rainfall raster).
#   2. Normalize values to 0–255 and convert to 8-bit unsigned.
#   3. Ensure final output is in SVY21 (EPSG:3414), consistent
#      with the rest of project.
#   4. The final 8-bit SVY21 GeoTIFF can be used for Mapbox
#      raster tileset upload.
#
# Aim:
#   - Clean, repeatable: every run deletes previous outputs.
# ============================================================

import os
import arcpy
from arcpy.sa import *

# ------------------------------------------------------------
# 0. ArcGIS / environment settings
# ------------------------------------------------------------

# Enable Spatial Analyst
arcpy.CheckOutExtension("Spatial")

# Allow overwriting outputs in this session
arcpy.env.overwriteOutput = True

# Controlled workspace for intermediate + final rasters
workspace_folder = r"C:\Users\zirui\Desktop\5219 final\rainfall realtime updater\output_data"
if not os.path.exists(workspace_folder):
    os.makedirs(workspace_folder)

arcpy.env.workspace = workspace_folder

# ------------------------------------------------------------
# 1. User-defined input and output variables
# ------------------------------------------------------------

# Input raster:
# - This should be generated by upstream script.
# - It can be in any CRS; this script will normalize it and
#   then project to SVY21 (EPSG:3414).
input_raster = os.path.join(workspace_folder, "comfort_score_latest.tif")

# Expected value range of the input raster (for normalization)
# Example: 0–100 comfort index.
input_min_value = 0.0
input_max_value = 100.0

# Intermediate normalized raster (same CRS as input)
normalized_raster_8bit_raw = os.path.join(workspace_folder, "comfort_8bit_raw.tif")

# Final normalized raster in SVY21 (EPSG:3414)
svy21_raster_8bit = os.path.join(workspace_folder, "comfort_8bit_3414.tif")

# ------------------------------------------------------------
# 2. Clean up previous outputs (idempotent run)
# ------------------------------------------------------------

# This ensures that each run starts fresh and does not
# accumulate old files with the same names.
for raster_path in [normalized_raster_8bit_raw, svy21_raster_8bit]:
    if arcpy.Exists(raster_path):
        print(f"Removing previous output: {raster_path}")
        arcpy.management.Delete(raster_path)

# ------------------------------------------------------------
# 3. Step A – Normalize raster to 0–255 (8-bit unsigned)
# ------------------------------------------------------------

print("Step A: Normalizing input raster to 0–255 (8-bit unsigned)...")
# aim to normalize the raster value to 0-255 to suit the mapbox upload format
# Check that the input raster exists
if not arcpy.Exists(input_raster):
    raise FileNotFoundError(
        f"Input raster not found: {input_raster}\n"
        f"Make sure upstream script created 'comfort_score_latest.tif'."
    )

# Load input raster
in_ras = Raster(input_raster)

# Compute value range for normalization
value_range = float(input_max_value) - float(input_min_value)
if value_range == 0:
    raise ValueError("Input_min_value and input_max_value are equal; cannot normalize.")

# Normalize to 0–1 by using below formula:
#   norm = (value - min) / (max - min)
norm_ras = (in_ras - input_min_value) / value_range

# clamp values to [0, 1] to avoid out-of-range artifacts
norm_ras = Con(norm_ras < 0, 0, norm_ras)
norm_ras = Con(norm_ras > 1, 1, norm_ras)

# Scale to 0–255
scaled_ras = norm_ras * 255

# Convert to integer (8-bit)
scaled_int = Int(scaled_ras)

# Save intermediate normalized raster
# - Still in the original CRS of input_raster
# - 8_BIT_UNSIGNED is required for compact, Mapbox-friendly tiles
arcpy.management.CopyRaster(
    in_raster=scaled_int,
    out_rasterdataset=normalized_raster_8bit_raw,
    pixel_type="8_BIT_UNSIGNED",
    format="TIFF",
    nodata_value=0
)

print(f" Normalized 8-bit raster saved (input CRS): {normalized_raster_8bit_raw}")

# ------------------------------------------------------------
# 4. Step B – Project normalized raster to SVY21 (EPSG:3414)
# ------------------------------------------------------------

print("Step B: Projecting normalized raster to SVY21 (EPSG:3414)...")

# Define SVY21 spatial reference
sr_svy21 = arcpy.SpatialReference(3414)

# Project the normalized raster into SVY21
# - If the input is already in 3414, this step is effectively
#   a no-op reprojection but keeps logic consistent.
# - BILINEAR is suitable for continuous comfort index surfaces.
arcpy.management.ProjectRaster(
    in_raster=normalized_raster_8bit_raw,
    out_raster=svy21_raster_8bit,
    out_coor_system=sr_svy21,
    resampling_type="BILINEAR"
)

print(f"SVY21 8-bit raster saved: {svy21_raster_8bit}")
print("Done. This SVY21 raster is ready for Mapbox upload step.")